fixed_objects:
  - name: drawer
  # - name: cupboard
  # - name: mailbox      
assets:  # in descending order of size
  - name: green bin
    number: 1
    model_path: environment/assets/bebs_custom/tote/small_tote.xml
    qpos_ranges:
      - 
        - 0.25
        - 0.55
      -
        - -0.35
        - 0.35
      -
        - 0.05
        - 0.05
      - 
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
  - name: red block
    number: 1
    model_path: environment/assets/bebs_custom/red_block.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
  - name: stick
    number: 1
    model_path: environment/assets/custom/stick.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
  # - name: drawer
  #   model_path: environment/assets/bebs_custom/small_drawer.xml
  #   qpos_ranges:
  #     -
  #       - 0.0
  #       - 0.1
  #     -
  #       - 0.6
  #       - 0.7
  #     -
  #       - 0.05
  #       - 0.05
  #     -
  #       - -2.1
  #       - -2.0
  #     -
  #       - 0.0
  #       - 0.0
  #     -
  #       - 0.0
  #       - 0.0
  #     -
  #       - 0.0
  #       - 0.0
  #     -
  #       - 0.0
  #       - 0.0
  #     -
  #       - 0.0
  #       - 0.4