fixed_objects:
  - name: drawer
  # - cupboard
assets:  # in descending order of size
  - name: green square
    number: 1
    model_path: environment/assets/square/green-square.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0
  - name: small violet block
    number: 1
    model_path: environment/assets/square/small_violet.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159