fixed_objects:
  - name: drawer
  # - cupboard
assets:  # in descending order of size
  - name: green bin
    number: 1
    model_path: environment/assets/bebs_custom/tote/small_tote.xml
    qpos_ranges:
      - 
        - 0.25
        - 0.55
      -
        - -0.35
        - 0.35
      -
        - 0.05
        - 0.05
      - 
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
  - name: school bus
    number: 1
    model_path: environment/assets/google_scanned_objects/toys/SCHOOL_BUS/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
  - name: teddy bear
    number: 1
    model_path: environment/assets/google_scanned_objects/Lovable_Huggable_Cuddly_Boutique_Teddy_Bear_Beige/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159