fixed_objects:
  - name: drawer
  #- cupboard
assets:  # in descending order of size
  - name: line
    number: 1
    model_path: environment/assets/line/line-template.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0
  - name: pencil case
    number: 1
    model_path: environment/assets/google_scanned_objects/household_items/Wishbone_Pencil_Case/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0