fixed_objects:
  - name: drawer
assets:  # in descending order of size
  - name: red block  # horse toy
    number: 1
    model_path: environment/assets/bebs_custom/red_block.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
  # - name: green square
  #   number: 2
  #   model_path: environment/assets/square/green-square.xml
  #   qpos_ranges:
  #     -
  #       - 0.2
  #       - 0.6
  #     -
  #       - -0.4
  #       - 0.4
  #     -
  #       - 0.2
  #       - 0.2
  #     -
  #       - 0
  #       - 0
  #     -
  #       - 0
  #       - 0
  #     -
  #       - -3.14159
  #       - 3.14159
  - name: turbo airplane toy
    number: 1
    model_path: environment/assets/google_scanned_objects/toys/TURBOPROP_AIRPLANE_WITH_PILOT/model.xml
    qpos_ranges:
      -
        - 0.4
        - 0.4
      -
        - -0.1
        - -0.1
      -
        - 0.2
        - 0.2
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0