fixed_objects:
  - name: drawer
  # - cupboard
assets:  # in descending order of size
  - name: blue bowl
    number: 1
    model_path: environment/assets/bowl/bowl.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0
  - name: grey bowl
    number: 1
    model_path: environment/assets/google_scanned_objects/household_items/Now_Designs_Bowl_Akita_Black/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - 0
        - 0
      -
        - 0
        - 0
      -
        - 0
        - 0