fixed_objects:
  - name: drawer
  # - cupboard
assets:  # in descending order of size
  - name: shoe
    number: 1
    model_path: environment/assets/google_scanned_objects/Womens_Bluefish_2Eye_Boat_Shoe_in_Tan/model.xml
    qpos_ranges:
      - 
        - 0.25
        - 0.55
      -
        - -0.35
        - 0.35
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
  - name: line
    number: 1
    model_path: environment/assets/line/line-template.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159