fixed_objects:
  #- drawer
  - name: cupboard
assets:  # in descending order of size
  - name: green bin
    number: 1
    model_path: environment/assets/bebs_custom/tote/small_tote.xml
    qpos_ranges:
      - 
        - 0.25
        - 0.55
      -
        - -0.35
        - 0.35
      -
        - 0.05
        - 0.05
      - 
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
  - name: coffee box
    number: 1
    model_path: environment/assets/google_scanned_objects/Nescafe_Momento_Mocha_Specialty_Coffee_Mix_8_ct/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - 0.0
        - 0.0 
  - name: scissor
    number: 1
    model_path: environment/assets/google_scanned_objects/Diamond_Visions_Scissors_Red/model.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      - 
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0
      -
        - 0.0
        - 0.0 