fixed_objects:
  - name: drawer
  - name: catapult
assets:
  - name: green block
    number: 1
    model_path: environment/assets/bowl/block.xml
    qpos_ranges:
      -
        - 0.2
        - 0.6
      -
        - -0.4
        - 0.4
      -
        - 0.2
        - 0.25
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159
      -
        - -3.14159
        - 3.14159